# Generated by Django 5.1.6 on 2025-03-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0004_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
