# Generated by Django 5.1.6 on 2025-03-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0006_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
