# Generated by Django 5.1.6 on 2025-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0010_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
