# Generated by Django 5.1.6 on 2025-03-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0011_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
