# Generated by Django 5.1.6 on 2025-03-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escan', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
